# Generated by Django 4.1.3 on 2022-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='word',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
