# Generated by Django 4.1.3 on 2022-11-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_definition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordDefinitions',
            new_name='WordDefinition',
        ),
    ]
